### ISSUE TITLE
Write readme with usage

### ISSUE THREAD

**Issue by leandroyalet** [rsksmart/rif-communications-js#17]
It should at minimum have following sections:

- [x]  Description what the tool does
- [x]  Installation
- [x]  Usage
- [x]  Contribute
- [x]  License
- [ ]  Fix the description to correctly explain intended use

This is a good example https://github.com/rsksmart/rif-storage-js

Refs rsksmart/rif-communications-node#4

**Comment by vojtechsimetka** [comment]
fixed in https://github.com/rsksmart/rif-communications-js/commit/484cbe4f364aaf3a04b8aadfdeefab3345f6abde
